### ISSUE TITLE
[PT-BR] Tradução da documentação

### ISSUE THREAD

**Issue by fdaciuk** [fdaciuk/hmh#7]
Precisamos traduzir a documentação do `hmh` para Português do Brasil.

As discussões gerais desse projeto deverão ser em inglês, mas essa issue, especificamente, pode ser discutida em português, já que tem relação com a tradução da documentação para pt-BR.

Se você gostaria de trabalhar nessa issue, sinalize aqui na issue, e vamos discutindo os detalhes de como deve ser feita essa tradução, ok? :)

**Comment by eduardojansen** [comment]
@fdaciuk , eu tenho interesse em contribuir nessa tradução.

**Comment by fdaciuk** [comment]
Oi @eduardojansen! Legal \o/
Você tem disponibilidade pra fazer isso para a Hacktoberfest? Se sim, eu já dou um _assing_ em você nessa issue, pois se mais alguém se interessar, já vai saber que você estará trabalhando nisso :)

**Comment by eduardojansen** [comment]
@fdaciuk, tenho sim :)

**Comment by fdaciuk** [comment]
Legal! Bom, minha ideia é bem simples: pode criar um diretório `docs` na raiz do projeto, copiar o `README.md` atual para esse diretório com o nome `pt-br.md`, e fazer a tradução nele.

Depois, só adicionar uma sessão no `README.md` principal com um link para `docs/pt-br.md`, só para as pessoas saberem que existe uma versão em pt-BR da doc.

O que acha? Tem alguma outra sugestão? :)

**Comment by eduardojansen** [comment]
Pra mim está ótimo dessa forma. Se surgir alguma outra ideia eu compartilho com você.

**Comment by fdaciuk** [comment]
Show! Se tiver dúvida de algo, pode postar aqui também :)

**Comment by eduardojansen** [comment]
@fdaciuk , mandei. Qualquer sugestão, me fala que vou ajustando.

**Comment by fdaciuk** [comment]
Boa! Já vou ver :D
